### ISSUE TITLE
[Config] Le fichier de configuration d'exemple ne fonctionne pas

### ISSUE THREAD

**Issue by mvergez** [PnX-SI/gn_module_ZH#9]
Le fichier de configuration : https://github.com/PnX-SI/gn_module_ZH/blob/main/config/conf_gn_module.toml.example est erroné au niveau de : 
```toml
# Renseigne le nom de la table permettant de remonter les observations
# de vertebrés effectuées à l'intérieur de la zones humide
vertebrates_view_name = {
    schema_name = "pr_zh",
    table_name = "vertebrates",
    category = "vertebrates"
}

# Renseigne le nom de la table permettant de remonter les observations
# d'invertebrés effectuées à l'intérieur de la zones humide
invertebrates_view_name = {
    schema_name = "pr_zh",
    table_name = "invertebrates",
    category = "invertebrates"
}

# Renseigne le nom de la table permettant de remonter les observations
# de flore effectuées à l'intérieur de la zones humide
flora_view_name = {
    schema_name = "pr_zh",
    table_name = "flora",
    category = "flora"
}
```
En effet, le formalisme TOML interdit le retour à la ligne, il faut donc remplacer cette section par : 
```toml
# Renseigne le nom de la table permettant de remonter les observations
# de vertebrés effectuées à l'intérieur de la zones humide
vertebrates_view_name = { schema_name = "pr_zh", table_name = "vertebrates", category = "vertebrates" }

# Renseigne le nom de la table permettant de remonter les observations
# d'invertebrés effectuées à l'intérieur de la zones humide
invertebrates_view_name = { schema_name = "pr_zh", table_name = "invertebrates", category = "invertebrates" }

# Renseigne le nom de la table permettant de remonter les observations
# de flore effectuées à l'intérieur de la zones humide
flora_view_name = { schema_name = "pr_zh", table_name = "flora", category = "flora" }
```

cf: https://github.com/PnX-SI/gn_module_ZH/commit/dfaa4d798a7aae4655f7942e754c9c1611f83257#r88753968

Nous ferons suivre une PR dans ce sens
